---
title: "Analysis of EMlab Generation 2"
author: "Marc Melliger & Emile Chappin"
date: "3/5/2020"
output: html_document
runtime: shiny
---

```{r setup, include=FALSE}

knitr::opts_chunk$set(echo = FALSE)

source(file = "scripts/init.R")

# theme for ggplot
theme_set(
  theme_bw(base_size = 13) + 
    theme(
      legend.title=element_blank(),
      panel.grid.major = element_blank(), 
      panel.grid.minor = element_blank(),
      legend.spacing.x = unit(0.1, 'cm')
    )
)

# In the init.R all results are read and common variables are prepared
source(file = "scripts/main.R")
```

Analysing result files with ID `r id` for scenario `r scenario`.

## Interactive part

```{r setup variables}

# variables for selection based on results
all_technologies <- get_sinlge_variable(data$operational_capacities_by_tech, technology)
technology_colors <- set_technology_colors(all_technologies)

all_producers <- get_sinlge_variable(data$cash_by_agents, producer)

## Shiny App

iteration_input <- function(input){
  seq(from = input$iterations[1], to = input$iterations[2], by = 1)
}

```


```{r Shiny App}
#library(shiny)
sidebarLayout(
  
  sidebarPanel(

    checkboxGroupInput("technologies_checked", label = h3("Technologies"), 
      choices = all_technologies,
      selected = all_technologies),
    
    hr(),
    
    sliderInput("iterations", label = h3("Iteration Range"), min = iteration_min, max = iteration_max, 
    value = c(iteration_min, iteration_max)),

    checkboxGroupInput("selected_producers", label = h3("Investors"), 
      choices = all_producers,
      selected = all_producers)
 
  
  ),

  mainPanel(

    tabsetPanel(
      type = "tabs",
      
      tabPanel(
        "Average", 
        
        renderPlot({plot_operational_capacities_average(input$technologies_checked, iteration_input(input))})
        
        # renderPlot({plot_generation_average(input$technologies_checked, iteration_input(input))}),
        # 
        # renderPlot({plot_cash_by_agents_average(input$selected_producers, iteration_input(input))})
        # 


        
        ),
      
    tabPanel(
      "Iterations",
       
      renderPlot({plot_operational_capacities_by_iterations(input$technologies_checked, iteration_input(input))})

      #  
      # renderPlot({plot_cash_by_agents_by_iterations(input$selected_producers, iteration_input(input))})
      


       
      )
    )
  )
)


```

```{r static example}

plot_operational_capacities_average(all_technologies, c(iteration_min, iteration_max))

  
# nice_colors = brewer.pal(n = 11, name = "Set3")
# technology_colors <- c(
#  "Coal PSC" = nice_colors[1],
#  "Lignite PSC" = nice_colors[2],
#  "Biomass CHP" = nice_colors[2],
#  "CCGT" = nice_colors[4],
#  "OCGT" = nice_colors[5],
#  "Fuel oil PGT" = nice_colors[6],
#  "Nuclear PGT" = nice_colors[7],
#  "Photovoltaic PGT" = nice_colors[8],
#  "Hydroelectric" = nice_colors[9],
#  "Onshore wind PGT" = nice_colors[10],
#  "Offshore wind PGT" = nice_colors[11]
# )


  


```


## TODOs

- Read in different scenarios, automically parse files
- Wholesale prices
- Things implemented previously
- For different agents.
- Distribution of cost of different costs
- Label stuff


```{r, echo=FALSE}
# 
#library(emlab)

# PlotCapacity(data_orig, detail = TRUE)
# 

# PlotCO2Emissions(data)
# PlotCO2Price(data)
# PlotCosts(data)
# PlotDuration(data)
# 
# PlotElectricityPrice(data,TRUE) 
# 
# PlotElectricityVolume(data)
# PlotNrPowerPlants(data)
# PlotPipelineCapacity(data)



# 
# PlotSubstancePrice(data)
# PlotSubstanceVolume(data)

# Missing load duration curve
# 

```

- Marketforecast

```{r}
# # Marketinfo --------------------------------------------------------------
# 
# prefix = paste(id, scenario, sep ="-")
# 
# filename = paste(prefix, "EMlabModelRole-DefaultReporter-MarketInformation.csv", sep = "-")
# marketForecast <- read_delim(paste0(directory, filename), delim = ";") %>% 
#   arrange(iteration, tick, segment)
# 
# 
# market_forecast_filtered <- marketForecast %>% 
#   mutate(
#     expectedSegmentLoadCausingVOLL = ifelse(result == 3, expectedSegmentLoad, NA)
#   ) %>% 
#   gather(
#     expectedSegmentLoad, segmentSupply, totalCapacityAvailable, 
#     key = "variable", value = "capacity") %>% 
#   filter(
#     # Just focus on one agent
#     agent == "Energy Producer NL B",
#     variable != "totalCapacityAvailable")
# 
# marketForecastPlot1 <-  market_forecast_filtered %>% 
#   ggplot(mapping = aes(x = segment, y = capacity, color = variable, linetype = agent)) +
#     geom_line() +
#     geom_point(mapping = aes(y = expectedSegmentLoadCausingVOLL), pch = 1, col = "blue") +
#     scale_y_log10() + 
#     facet_wrap(~ tick) + 
#     labs(
#       title = "Expected Market Information")
# marketForecastPlot1
#   
# marketForecastPlot2 <- market_forecast_filtered %>% 
#   ggplot(mapping = aes(x = segment, y = expectedElectricityPrice, linetype = agent)) +
#   geom_line() +
#   scale_y_log10() + 
#   facet_wrap(~ tick) + 
#   labs(
#     title = "Expected Electrictiy Prices")
# marketForecastPlot2
# 
# ggsave(filename = paste0("output/", prefix, "-marketForecastPlot1.pdf"), plot = marketForecastPlot1, width = 10, height = 6)
# ggsave(filename = paste0("output/", prefix, "-marketForecastPlot2.pdf"), plot = marketForecastPlot2, width = 10, height = 6)

```


